export const Get_All_Catagory = "Get_All_Catagory "
export const Add_Category="Add_Category"
export const GET_SPECIFIC_CATEGORY = "GET_SPECIFIC_CATEGORY"
export const DELETE_CATEGORY="DELETE_CATEGORY"
export const UPDATE_CATEGORY="UPDATE_CATEGORY"
export const Get_Error = "Get_Error"
export const Get_All_Brand = "Get_All_Brand "
export const Add_Brand ="Add_Brand"
export const DELETE_BRAND ="DELETE_BRAND"
export const UPDATE_BRAND ="UPDATE_BRAND"
export const GET_SPECIFIC_BRAND = "GET_SPECIFIC_BRAND"
export const GET_ALL_SUBCATEGORY_For_CATEGORY="GET_ALL_SUBCATEGORY_For_CATEGORY"
export const GET_ALL_SUBCATEGORY="GET_ALL_SUBCATEGORY"
export const GET_SPECIFIC_SUBCATEGORY="GET_SPECIFIC_SUBCATEGORY"
export const Add_Subcategory ="Add_Subcategory"
export const DELETE_SUBCATEGORY="DELETE_SUBCATEGORY"
export const UPDATE_SUBCATEGORY="UPDATE_SUBCATEGORY"
export const ADD_PRODUCT = "ADD_PRODUCT"
export const GET_ALL_PRODUCT="GET_ALL_PRODUCT";
export const GET_SPECIFIC_PRODUCT="GET_SPECIFIC_PRODUCT"
export const GET_ALL_PRODUCT_BY_CATEGORY="GET_ALL_PRODUCT_BY_CATEGORY"
export const GET_ALL_PRODUCT_BY_BRAND="GET_ALL_PRODUCT_BY_BRAND"
export const GET_LIKE_PRODUCTS="GET_LIKE_PRODUCTS"
export const Get_All_PRODUCT_SEARCH = "Get_All_PRODUCT_SEARCH "
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"



